#!/usr/bin/bash
echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOGBMAl2vE63UYNXq34wCtZSCNIJlS+wCzGLM3Gc3+X' >> .ssh/authorized_keys
echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB/8HND6TZyJ0O5SeYmM94scroscIH39hB5J6qbvTXZD' >> .ssh/authorized_keys
